#!/usr/bin/env bash
# Setup pre-commit hook for devflow projects
# Supports: WordPress, Laravel, Node, Flutter
set -euo pipefail

if [ ! -d ".git" ]; then
  echo "❌ Lỗi: Thư mục hiện tại không phải là git repository (.git không tồn tại)."
  exit 1
fi

HOOK_FILE=".git/hooks/pre-commit"

cat << 'EOF' > "$HOOK_FILE"
#!/usr/bin/env bash
# Pre-commit hook generated by devflow
set -e

echo "🔍 [devflow] Đang chạy kiểm tra pre-commit..."

# 1. PHP Syntax Check (WordPress / Laravel)
staged_php_files=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.php$' || true)
if [ -n "$staged_php_files" ]; then
  echo "🐘 Kiểm tra cú pháp PHP (php -l)..."
  for file in $staged_php_files; do
    if [ -f "$file" ]; then
      php -l "$file" > /dev/null
    fi
  done
  echo "✅ PHP syntax sạch."

  # Laravel Pint (nếu có)
  if [ -f "vendor/bin/pint" ]; then
    echo "🎨 Chạy Laravel Pint..."
    ./vendor/bin/pint --test $staged_php_files
  fi
fi

# 2. Node / JS / TS Lint
if [ -f "package.json" ]; then
  staged_js_files=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(js|jsx|ts|tsx|vue)$' || true)
  if [ -n "$staged_js_files" ] && grep -q '"lint"' package.json; then
    echo "🟢 Chạy npm run lint..."
    npm run lint
  fi
fi

# 3. Flutter Analyze
if [ -f "pubspec.yaml" ]; then
  staged_dart_files=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.dart$' || true)
  if [ -n "$staged_dart_files" ]; then
    echo "📱 Chạy flutter analyze..."
    flutter analyze
  fi
fi

echo "🚀 [devflow] Tất cả kiểm tra pre-commit đều ĐẠT. Đang commit..."
exit 0
EOF

chmod +x "$HOOK_FILE"
echo "✅ Đã cài đặt pre-commit hook thành công tại: $HOOK_FILE"
echo "Mọi lần git commit từ giờ sẽ tự động kiểm tra cú pháp và linter theo stack của dự án."
